@SocialNetwork.API_HostAddress = https://localhost:5000

POST {{SocialNetwork.API_HostAddress}}/api/account/login
Accept: */*
Content-Type: application/json

{
    "username": "rose",
    "password": "Pa$$w0rd"
}


###
POST {{SocialNetwork.API_HostAddress}}/api/account/register
Accept: */*
Content-Type: application/json

{
    "username": "string",
    "email": "string",
    "knownAs": "string",
    "gender": "string",
    "dateOfBirth": "2023-12-05T13:37:23.353Z",
    "password": "string"
}

###
GET {{SocialNetwork.API_HostAddress}}/api/users
Accept: */*
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxIiwidW5pcXVlX25hbWUiOiJyb3NlIiwibmJmIjoxNzAyNzgyMDMzLCJleHAiOjE3MDMzODY4MzMsImlhdCI6MTcwMjc4MjAzM30.F27Lyl9tp9HnMqPtQtFT85zDR2RREs3uEMmukmsqLJNKRQioa1W-vUL6zxi387AT4gBnTnTD1aZaFXQHEpVSew

###
GET {{SocialNetwork.API_HostAddress}}/api/users/rose
Accept: */*
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxIiwidW5pcXVlX25hbWUiOiJyb3NlIiwibmJmIjoxNzAyNzgyMDMzLCJleHAiOjE3MDMzODY4MzMsImlhdCI6MTcwMjc4MjAzM30.F27Lyl9tp9HnMqPtQtFT85zDR2RREs3uEMmukmsqLJNKRQioa1W-vUL6zxi387AT4gBnTnTD1aZaFXQHEpVSew

###
POST {{SocialNetwork.API_HostAddress}}/api/users/create-post
Accept: */*
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxIiwidW5pcXVlX25hbWUiOiJyb3NlIiwibmJmIjoxNzAyNzgyMDMzLCJleHAiOjE3MDMzODY4MzMsImlhdCI6MTcwMjc4MjAzM30.F27Lyl9tp9HnMqPtQtFT85zDR2RREs3uEMmukmsqLJNKRQioa1W-vUL6zxi387AT4gBnTnTD1aZaFXQHEpVSew

{
    Content: "Xin chào các bạn"
    Files: 74882983_1134695023403533_7193827056931569664_n.jpg
}




















